kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-manager-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["watch", "list", "create", "update", "delete"]