kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-manager-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: ingress-manager-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: ingress-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io